// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX-ooKDA4zMNVUXvvr7yO9seRZXyrauaw',
    appId: '1:591097032249:web:33fcc9d86698dbe6ffa7e8',
    messagingSenderId: '591097032249',
    projectId: 't-ecommerce-app-d8687',
    authDomain: 't-ecommerce-app-d8687.firebaseapp.com',
    storageBucket: 't-ecommerce-app-d8687.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzIxmFC4pVzWyL04_-IFTHUFbfWWav_CI',
    appId: '1:591097032249:android:e11f86b94fafcf6effa7e8',
    messagingSenderId: '591097032249',
    projectId: 't-ecommerce-app-d8687',
    storageBucket: 't-ecommerce-app-d8687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwHNCQJJkkMDOS9LQleJZdvOIyRb8z0MU',
    appId: '1:591097032249:ios:206d4f2d4eb5aaa9ffa7e8',
    messagingSenderId: '591097032249',
    projectId: 't-ecommerce-app-d8687',
    storageBucket: 't-ecommerce-app-d8687.appspot.com',
    androidClientId: '591097032249-2g44kktj3k0mc1163het3qfihlkjv9jv.apps.googleusercontent.com',
    iosClientId: '591097032249-pus2il0m2sogar7khcrubqpprqccdksr.apps.googleusercontent.com',
    iosBundleId: 'com.isam.elzobi.tecommerce.tEcommerceAdminPanel',
  );

}